"""rename department model table name

Revision ID: 234eb5dbc33c
Revises: db2df52da672
Create Date: 2024-06-26 15:18:17.387909

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "234eb5dbc33c"
down_revision = "db2df52da672"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "department")
    # ### end Alembic commands ###
