"""rename address to location

Revision ID: 7f97f9f7a3c3
Revises: 234eb5dbc33c
Create Date: 2024-06-27 09:27:51.885502

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7f97f9f7a3c3"
down_revision = "234eb5dbc33c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "address", new_column_name="location")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "location", new_column_name="address")
    # ### end Alembic commands ###
